[package]
name = "gfautil"
version = "0.1.0"
authors = ["christian <christian@chfi.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gfa = { path = "../rs-gfa" }
handlegraph = { path = "../rs-handlegraph" }
# gfa = "0.6.1"
# handlegraph = "0.3"
clap = "2.33"
structopt = "0.3"
rayon = "1"
serde = { version = "1.0", features = ["derive"] }
bstr = "0.2"
